import { PDReportData } from './types';

export const sampleKulwantSingh: PDReportData = {
  shopNo: '',
  visitDate: '03/10/2026',
  visitLocation: 'Narbad Khera',
  customerName: 'Kulwant Singh',
  residenceType: 'Self Owned',
  residenceStabilityNotes: 'Living since birth (approx 48 yrs) - Stable ancestral stay',
  propertyAddress: 'Narbad Khera Narbad Khera Beawar Ajmer-305901',
  permanentAddress: 'Same as',
  contactNumbers: '9876543210 , 9876543201',
  distNearestBranch: 'BEAWAR - 15km',
  distSourcingBranch: 'BEAWAR - 15km',
  locationType: 'Rural',
  businessNameAddress: 'SAWAN MOTOR DRIVING SCHOOL, Udaipur Road Chungi Naka BEAWAR',
  businessVintage: '25 YEARS',
  businessPremises: 'Rent / Ram Lal - 9876543210',
  monthlyIncomeDetails: 'Driving training fees @ Rs. 3,500/student. Average 25-30 candidates/month. Net monthly earnings approx Rs. 75,000 to Rs. 85,000.',
  considerIncomeDetails: 'Assessed business vintage 25 yrs with stable local reputation. Assessed disposable monthly income Rs. 55,000 after business fuel and maintenance expenses.',
  neighbourRef1: 'Ramesh Singh 9876543202',
  neighbourRef2: 'Pushpendra Singh 9876543203',
  businessRef1: 'Sonu 9876543204',
  businessRef2: 'Ganpat Singh 9876543205',
  familyMembers: [
    { id: '1', name: 'Kulwant Singh s/o Chimman Singh', age: '48', relation: 'Self', business: 'Driving School' },
    { id: '2', name: 'Rekha w/o Kulwant Singh', age: '39', relation: 'Wife', business: 'House wife' },
    { id: '3', name: 'Chitransha d/o Kulwant Singh', age: '20', relation: 'Daughter', business: 'Student' },
    { id: '4', name: 'Manshika d/o Kulwant Singh', age: '18', relation: 'Daughter', business: 'Student' },
    { id: '5', name: 'Bhumika d/o Kulwant Singh', age: '16', relation: 'Daughter', business: 'Student' },
    { id: '6', name: 'Chandra Kanta d/o Kulwant Singh', age: '12', relation: 'Daughter', business: 'Student' },
    { id: '7', name: 'Kushumlatta d/o Kulwant Singh', age: '10', relation: 'Daughter', business: 'Student' },
    { id: '8', name: 'Supriya d/o Kulwant Singh', age: '7', relation: 'Daughter', business: 'Student' },
    { id: '9', name: 'Parag Raj Singh s/o Kulwant Singh', age: '1', relation: 'Son', business: '--' },
    { id: '10', name: '', age: '', relation: '', business: '' }
  ],
  masterTreeNotes: `Late Chimman Singh (Father)
  └── Kulwant Singh (Applicant, Age 48) + Rekha Devi (Co-Applicant / Property Owner, Age 39)
        ├── Chitransha (Daughter, 20 yrs - Student)
        ├── Manshika (Daughter, 18 yrs)
        ├── Bhumika (Daughter, 16 yrs)
        ├── Chandra Kanta (Daughter, 12 yrs)
        ├── Kushumlatta (Daughter, 10 yrs)
        ├── Supriya (Daughter, 7 yrs)
        └── Parag Raj Singh (Son, 1 yr)`,
  guarantorDetail: 'Guarantor Not Add at PD Visit Time',
  cibilAppName: 'KULWANT',
  cibilAppScore: '697',
  cibilCoApp1Name: 'REKHA DEVI',
  cibilCoApp1Score: '-1',
  cibilCoApp2Name: '',
  cibilCoApp2Score: '',
  cibilCoApp3Name: '',
  cibilCoApp3Score: '',
  existingLoans: 'Nil major defaults, 1 small two-wheeler cleared.',
  runningObligations: 'Rs. 4,200/month',
  assetVehicleDetails: '2 Maruti 800 / Alto training cars, self-owned residential house.',
  legalStatus: 'Perfect',
  propertyTitle: 'Reg. GP PATTA',
  propertyOwner: 'REKHA DEVI',
  electricityDetails: 'K.No. 100000000001 - Name: Rekha Devi w/o Kulwant Singh (Paid regular)',
  marketValue: 'Rs. 24,50,000 /-',
  endUseLoan: 'Business expansion & vehicle fleet upgrade',
  monthlyEmiPaid: 'Comfortably serviceable via driving school cash flow',
  waiver: 'NA',
  requiredDocs: 'Updated Bank Statement (6 Mos), Registration certificate of driving school, GP Patta original verification',
  deviationFindings: 'Co-applicant CIBIL score is -1 (New to credit). Applicant score 697 is satisfactory with clean track record.',
  remarksNotes: 'Applicant has strong local standing and vintage of 25 years in Beawar city. Physical residence and business premises verified on site.',
  mitigateNotes: 'Co-applicant is homemaker and co-owner of title deed; primary borrower cash-flow is adequate to service proposed EMI.',
  recommendation: 'Recommended',
  dirNorth: 'Plot of Shri Ram Lal',
  dirSouth: 'Main 30 ft Village Road',
  dirEast: 'House of Rameshwar Ji',
  dirWest: 'Open Government Land',
  propertySize: 'SAME AS PATTA',
  pdAuthorisedPerson: 'Manish Kumar (Credit Manager)',
  signDate: '03/10/2026'
};

export const sampleRajeshSharma: PDReportData = {
  shopNo: '48902154',
  visitDate: '04/10/2026',
  visitLocation: 'Mansarovar, Jaipur',
  customerName: 'Rajesh Kumar Sharma',
  residenceType: 'Self Owned',
  residenceStabilityNotes: 'Own residence since 2012 (14+ yrs stay)',
  propertyAddress: 'Plot No. 124, Sector 7, Mansarovar, Jaipur - 302020',
  permanentAddress: 'Same as',
  contactNumbers: '9876543211 , 9876543212',
  distNearestBranch: 'JAIPUR MANSAROVAR - 3.5km',
  distSourcingBranch: 'JAIPUR MANSAROVAR - 3.5km',
  locationType: 'Urban',
  businessNameAddress: 'SHARMA PROVISION & GENERAL STORE, Shop 4, Main Market, Sec 7 Mansarovar',
  businessVintage: '14 YEARS',
  businessPremises: 'Self Owned Shop',
  monthlyIncomeDetails: 'Daily sales Rs. 28,000 - Rs. 35,000. Gross monthly turnover ~Rs. 9,50,000. Net margin 14-16%. Assessed net monthly profit Rs. 1,40,000.',
  considerIncomeDetails: 'Assessed monthly disposable income Rs. 1,15,000 based on bank credits, QR code transaction sheets, and supplier invoices.',
  neighbourRef1: 'Kailash Meena 9876543213',
  neighbourRef2: 'Satish Agarwal 9876543214',
  businessRef1: 'Goyal Wholesalers 9876543215',
  businessRef2: 'Shree Krishna Traders 9876543216',
  familyMembers: [
    { id: '1', name: 'Rajesh Kumar Sharma s/o O.P. Sharma', age: '44', relation: 'Self', business: 'Grocery Business' },
    { id: '2', name: 'Sunita Sharma w/o Rajesh Sharma', age: '41', relation: 'Wife', business: 'Assists in store' },
    { id: '3', name: 'Aayush Sharma s/o Rajesh Sharma', age: '19', relation: 'Son', business: 'College Student (B.Com)' },
    { id: '4', name: 'Ananya Sharma d/o Rajesh Sharma', age: '15', relation: 'Daughter', business: 'Student (Class 10)' },
    { id: '5', name: 'Om Prakash Sharma (Father)', age: '72', relation: 'Father', business: 'Retired Pensioner' },
    { id: '6', name: '', age: '', relation: '', business: '' },
    { id: '7', name: '', age: '', relation: '', business: '' },
    { id: '8', name: '', age: '', relation: '', business: '' },
    { id: '9', name: '', age: '', relation: '', business: '' },
    { id: '10', name: '', age: '', relation: '', business: '' }
  ],
  masterTreeNotes: `Om Prakash Sharma (Father, 72 yrs - Retired)
  └── Rajesh Kumar Sharma (Applicant, 44 yrs) + Sunita Sharma (Co-App, 41 yrs)
        ├── Aayush Sharma (Son, 19 yrs - College)
        └── Ananya Sharma (Daughter, 15 yrs - School)`,
  guarantorDetail: 'Guarantor Added: Om Prakash Sharma (Father, Pensioner)',
  cibilAppName: 'RAJESH SHARMA',
  cibilAppScore: '742',
  cibilCoApp1Name: 'SUNITA SHARMA',
  cibilCoApp1Score: '710',
  cibilCoApp2Name: 'O P SHARMA',
  cibilCoApp2Score: '768',
  cibilCoApp3Name: '',
  cibilCoApp3Score: '',
  existingLoans: 'Auto loan running with HDFC Bank (EMI Rs. 14,800), clean track record.',
  runningObligations: 'Rs. 14,800/month',
  assetVehicleDetails: 'Hyundai Creta 2021 model, Self-owned commercial shop + 3 BHK house.',
  legalStatus: 'Perfect',
  propertyTitle: 'JDA Approved Patta & Registered Sale Deed',
  propertyOwner: 'RAJESH KUMAR SHARMA & SUNITA SHARMA',
  electricityDetails: 'K.No. 100000000002 - Name: Rajesh Kumar Sharma (Paid regular)',
  marketValue: 'Rs. 82,00,000 /-',
  endUseLoan: 'Working capital & stock procurement for festival season',
  monthlyEmiPaid: 'Comfortably covered (FOIR ~ 32%)',
  waiver: 'None',
  requiredDocs: 'GST Returns (12 Mos), ITR of 2 years, JDA Patta copy & Chain deeds',
  deviationFindings: 'No major deviation. Excellent credit track and healthy banking turnover.',
  remarksNotes: 'Prime residential and commercial locality in Mansarovar. High business footfall and established customer base.',
  mitigateNotes: 'Healthy debt-service coverage ratio of 2.8x. Adequate safety margin on collateral.',
  recommendation: 'Recommended',
  dirNorth: 'Plot No. 125',
  dirSouth: 'Plot No. 123',
  dirEast: '40 Ft Colony Road',
  dirWest: 'Neighbour Property Backside',
  propertySize: 'SAME AS PATTA',
  pdAuthorisedPerson: 'Amitabh Verma (Chief Credit Officer)',
  signDate: '04/10/2026'
};

export const blankReport: PDReportData = {
  shopNo: '',
  visitDate: new Date().toLocaleDateString('en-GB'),
  visitLocation: '',
  customerName: '',
  residenceType: 'Self Owned',
  residenceStabilityNotes: '',
  propertyAddress: '',
  permanentAddress: '',
  contactNumbers: '',
  distNearestBranch: '',
  distSourcingBranch: '',
  locationType: 'Semi-Urban',
  businessNameAddress: '',
  businessVintage: '',
  businessPremises: '',
  monthlyIncomeDetails: '',
  considerIncomeDetails: '',
  neighbourRef1: '',
  neighbourRef2: '',
  businessRef1: '',
  businessRef2: '',
  familyMembers: Array.from({ length: 10 }, (_, i) => ({
    id: `${i + 1}`,
    name: '',
    age: '',
    relation: '',
    business: ''
  })),
  masterTreeNotes: '',
  guarantorDetail: 'Guarantor Not Add at PD Visit Time',
  cibilAppName: '',
  cibilAppScore: '',
  cibilCoApp1Name: '',
  cibilCoApp1Score: '',
  cibilCoApp2Name: '',
  cibilCoApp2Score: '',
  cibilCoApp3Name: '',
  cibilCoApp3Score: '',
  existingLoans: '',
  runningObligations: '',
  assetVehicleDetails: '',
  legalStatus: 'Perfect',
  propertyTitle: '',
  propertyOwner: '',
  electricityDetails: '',
  marketValue: '',
  endUseLoan: '',
  monthlyEmiPaid: '',
  waiver: '',
  requiredDocs: '',
  deviationFindings: '',
  remarksNotes: '',
  mitigateNotes: '',
  recommendation: 'Recommended',
  dirNorth: '',
  dirSouth: '',
  dirEast: '',
  dirWest: '',
  propertySize: 'SAME AS PATTA',
  pdAuthorisedPerson: '',
  signDate: new Date().toLocaleDateString('en-GB')
};
